### ISSUE TITLE
OK / Enter / Select button does not work

### ISSUE THREAD

**Issue by tskyfe** [AppGround-io/bluetooth-keyboard-and-mouse-support#50]
When using app with Sony Bravia Android TV Oreo, Beach Buggy Racing, the centre button of the Multimedia pad doesn't work.
Hence although I am able to navigate around the game menu, I cannot enter into any of the options.

**Comment by tskyfe** [comment]
I did more testing, the mouse pad on Multimedia pad does not allow clicking as well.
When i switch back to just the Mouse pad, I can click.

**Comment by AppGround-io** [comment]
Thank you for the report. The problems in the multimedia mode are fixed in the beta version 2.10.0

**Comment by tskyfe** [comment]
Hi thanks for the quick fix.

i have verified that the mouse pad can click items.

However, the following buttons (multimedia mode) still do not work within the game on an Android TV.

1. The OK button (I tested this with other remote apps and their OK button works, so might just be some mapping issue?)
This button works within the Android TV UI, but once enter the game, it doesnt register.
2. The Home button
3. The Back button

Other buttons that do not have a reaction within the game:
- Play / Pause
- Menu
But I think these are ok since probably it is not supported in the game.

**Comment by AppGround-io** [comment]
This is a really strange problem and I spend some time yesterday to figure this out.
My test setup was a Nvidia Shield Android TV and a Samsung Tab S4 tablet with a Fire TV Remote and of course the app.
I tested Beach Buggy Racing and there seems to be a different behavior on the tablet and Android TV:
- Back button works on both remotes only on the tablet but not on Android TV
- Home button works with both remotes on both devices
- The OK/Center button is really strange. It works only on Android TV and only with the Fire TV remote. There seems to be a special handling of the Fire TV remote on Android TV, because the key that I send with the app is the same as the Fire TV remote is sending.

So it's a combination of Android and game related problems, not much I can do currently to fix this. Gamepad support is coming soon, this should work with the game as well.

**Comment by tskyfe** [comment]
Yup you are absolutely right.




I love your work. Bought premium and was testing out the app on more scenarios.




Yes, in multimedia mode, in YouTube app on Android TV, the back button does not work as well.


Some other remote apps from the Play Store works.




Yes I am wondering is it a case of two different keys for the OK button.


Is it possible to map two keys for a single button?


Maybe there is one key for "Enter", and another key for "Confirm"?




Obviously I am no expert here and may just be going off tangent.




I think a server less gamepad that works on Android TV is definitely a first on the PlayStore.


Would be a game changer if the gamepad works.






Tony




Get Outlook for Android







On Fri, Jun 26, 2020 at 5:03 PM +0800, "AppGround-io" <notifications@github.com> wrote:















Closed #50.

**Comment by tskyfe** [comment]
https://developer.android.com/training/tv/start/controllers
